[package]

name = "fps_counter"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "eddyb"
]
tags = []

[lib]

name = "fps_counter"
path = "src/lib.rs"

[dependencies.time]

git = "http://github.com/rust-lang/time"

